# Generated by Django 4.0.6 on 2022-07-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='books_sale',
        ),
    ]
